export const apiRouteList = [
    {
        path: '/',
        component: 'Layout',
        redirect: '/overview',
        icon: 'icon-shouye1',
        noDropdown: true,
        meta: {},
        children: [
            {
                path: 'overview',
                component: 'overview/overview',
                name: 'overview',
                meta: {title: '首页'},
            },
        ],
    },
    {
        path: '/systemSetting',
        component: 'Layout',
        name: 'systemSetting',
        meta: {title: '系统管理'},
        icon: 'icon-xitong',
        redirect: '/systemSetting/organizationList',
        children: [
            {
                path: 'organizationList',
                component: 'systemSetting/organization/organizationList',
                name: 'organizationList',
                meta: {title: '组织管理', btnPermissions: []},
            },
            {
                path: 'projectList',
                component: 'systemSetting/project/projectList',
                name: 'projectList',
                meta: {
                    title: '项目管理',
                    btnPermissions: [
                        {menuButtonCode: 'create'},
                        {menuButtonCode: 'edit'},
                        {menuButtonCode: 'delete'},
                    ],
                },
            },
            {
                path: 'projectNew',
                component: 'systemSetting/project/table/create',
                name: 'projectNew',
                meta: {title: '新建项目', keepAlive: true},
                hidden: true,
            },
            {
                path: 'projectEdit',
                component: 'systemSetting/project/table/edit',
                name: 'projectEdit',
                meta: {title: '编辑项目', keepAlive: true},
                hidden: true,
            },
            {
                path: 'userList',
                component: 'systemSetting/user/userList',
                name: 'userList',
                meta: {
                    title: '用户管理',
                    btnPermissions: [
                        {menuButtonCode: 'create'},
                        {menuButtonCode: 'edit'},
                        {menuButtonCode: 'delete'},
                    ],
                },
            },
            {
                path: 'userNew',
                component: 'systemSetting/user/table/create',
                name: 'userNew',
                meta: {title: '新建用户', keepAlive: true},
                hidden: true,
            },
            {
                path: 'userEdit',
                component: 'systemSetting/user/table/edit',
                name: 'userEdit',
                meta: {title: '编辑用户', keepAlive: true},
                hidden: true,
            },
            {
                path: 'userDetail',
                component: 'systemSetting/user/table/detail',
                name: 'userDetail',
                meta: {title: '用户详情', keepAlive: true},
                hidden: true,
            },
            {
                path: 'authorizationList',
                component: 'systemSetting/authorization/authorizationList',
                name: 'authorizationList',
                meta: {title: '权限管理', btnPermissions: []},
            },
            {
                path: 'dictionaryList',
                component: 'systemSetting/dictionary/dictionaryList',
                name: 'dictionaryList',
                meta: {title: '数据字典', btnPermissions: []},
            },
            {
                path: 'routerMenuList',
                component: 'systemSetting/routerMenu/routerMenuList',
                name: 'routerMenuList',
                meta: {title: '菜单管理', btnPermissions: []},
            },
            {
                path: 'onlineManualsList',
                component: 'systemSetting/onlineManuals/onlineManualsList',
                name: 'onlineManualsList',
                meta: {
                    title: '知识库管理',
                    btnPermissions: [
                        {menuButtonCode: 'create'},
                        {menuButtonCode: 'edit'},
                        {menuButtonCode: 'delete'},
                    ],
                },
            },
            {
                path: 'ruleConfigurationList',
                component: 'systemSetting/ruleConfiguration/ruleConfigurationList',
                name: 'ruleConfigurationList',
                meta: {title: '规则管理', btnPermissions: []},
            },
            {
                path: 'operationLogList',
                component: 'systemSetting/operationLog/operationLogList',
                name: 'operationLogList',
                meta: {title: '操作日志', btnPermissions: []},
            },
        ],
    },
    {
        path: '/implementationManagement',
        component: 'Layout',
        name: 'implementationManagement',
        meta: {title: '研发项目实施管理'},
        icon: 'icon-xitong',
        redirect: '/implementationManagement/contract',
        children: [
            {
                path: 'contractList',
                component: 'implementationManagement/contract/contractList',
                name: 'contractList',
                meta: {
                    title: '研发项目合同签订',
                    btnPermissions: [
                        {menuButtonCode: 'create'},
                        {menuButtonCode: 'edit'},
                        {menuButtonCode: 'delete'},
                    ],
                },
            },
            {
                path: 'contractNew',
                component: 'implementationManagement/contract/table/create',
                name: 'contractNew',
                meta: {title: '新建研发项目合同签订', keepAlive: true},
                hidden: true,
            },
            {
                path: 'contractEdit',
                component: 'implementationManagement/contract/table/edit',
                name: 'contractEdit',
                meta: {title: '编辑研发项目合同签订', keepAlive: true},
                hidden: true,
            },
            {
                path: 'disclosureList',
                component: 'implementationManagement/disclosure/disclosureList',
                name: 'disclosureList',
                meta: {
                    title: '项目技术经济交底书',
                    btnPermissions: [
                        {menuButtonCode: 'create'},
                        {menuButtonCode: 'edit'},
                        {menuButtonCode: 'delete'},
                    ],
                },
            },
            {
                path: 'disclosureNew',
                component: 'implementationManagement/disclosure/table/create',
                name: 'disclosureNew',
                meta: {title: '新增项目技术经济交底书', keepAlive: true},
                hidden: true,
            },
            {
                path: 'disclosureEdit',
                component: 'implementationManagement/disclosure/table/edit',
                name: 'disclosureEdit',
                meta: {title: '编辑项目技术经济交底书', keepAlive: true},
                hidden: true,
            },
            {
                path: 'reportList',
                component: 'implementationManagement/report/reportList',
                name: 'reportList',
                meta: {
                    title: '研发项目进展报告',
                    btnPermissions: [
                        {menuButtonCode: 'create'},
                        {menuButtonCode: 'edit'},
                        {menuButtonCode: 'delete'},
                    ],
                },
            },
            {
                path: 'reportNew',
                component: 'implementationManagement/report/table/create',
                name: 'reportNew',
                meta: {title: '新增研发项目进展报告', keepAlive: true},
                hidden: true,
            },
            {
                path: 'reportEdit',
                component: 'implementationManagement/report/table/edit',
                name: 'reportEdit',
                meta: {title: '编辑研发项目进展报告', keepAlive: true},
                hidden: true,
            },
        ],
    },
];
