#tomcat服务端口号
server:
  port: 8090

#mybatis数据源配置
#spring:
#  datasource:
#    mybatis:
#      name: mybatis
#      jdbc-url: jdbc:mysql://localhost:3306/AISaas?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: root
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#    mybatis2:
#      name: mybatis2
#      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: root
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20